import jsPDF from "jspdf";

function categoryIcon(cat) {
  const map = { food: "[Food]", sightseeing: "[Sight]", adventure: "[Adventure]", culture: "[Culture]", shopping: "[Shop]", relaxation: "[Relax]", nightlife: "[Night]" };
  return map[cat] || "[Other]";
}

function renderDay(doc, day, startY, pageWidth, margin) {
  const activities = day.activities || [];
  const lineH = 6;
  let y = startY;
  const col2 = pageWidth - margin - 50;
  const maxW = col2 - margin - 10;

  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text(`Day ${day.day}${day.date ? ` — ${day.date}` : ""}`, margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  for (const act of activities) {
    const time = act.time || "";
    const name = act.name || "";
    const cost = act.cost || "";
    const cat = act.category || "";
    const dur = act.duration || "";

    const icon = categoryIcon(cat);
    const line = `${icon} ${time ? time + "  " : ""}${name}`;
    const details = [dur, cost].filter(Boolean).join("  ·  ");

    if (y > 270) {
      doc.addPage();
      y = 20;
    }

    doc.text(line, margin + 4, y, { maxWidth: maxW });
    y += lineH;

    if (details) {
      doc.setFontSize(8);
      doc.setTextColor(100);
      doc.text(details, margin + 12, y);
      doc.setTextColor(0);
      doc.setFontSize(10);
      y += lineH + 2;
    } else {
      y += 2;
    }
  }

  return y + 4;
}

export async function exportTripPdf(trip) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const margin = 18;
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = margin;

  const days = trip.itinerary?.days || [];

  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(trip.title || "Trip Itinerary", margin, y);
  y += 10;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80);
  const meta = [`Destination: ${trip.destination}`];
  if (trip.budget) meta.push(`Budget: ${trip.budget}`);
  meta.push(`${days.length} day${days.length !== 1 ? "s" : ""}`);
  doc.text(meta.join("  ·  "), margin, y);
  y += 8;

  if (trip.budget_summary) {
    const bs = trip.budget_summary;
    doc.setFontSize(10);
    doc.setTextColor(0, 150, 100);
    doc.text(`Total estimated cost: ${bs.currency || ""}${bs.total_cost?.toFixed(2) || "0.00"}`, margin, y);
    y += 10;
    doc.setTextColor(0);
  }

  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 6;

  for (const day of days) {
    if (y > 260) {
      doc.addPage();
      y = 20;
    }
    y = renderDay(doc, day, y, pageWidth, margin);
  }

  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by AI Travel Planner", margin, 290);

  doc.save(`${trip.destination || "trip"}-itinerary.pdf`);
}
